version: '3.8'

services:
  db:
    container_name: batch-db
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbscripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=batch_db
    env_file:
      - ./.env
    ports:
      - 5442:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
        
volumes:
  postgres_data: